---

#- name: we need awscli on 8
#  pip:
#    name: awscli
#    executable: pip3
#  when: (ansible_os_family == "RedHat") and
#        (ansible_distribution_major_version) == "8"

- name: AWS CLI OS-included binary for now
  ansible.builtin.package:
    name: awscli
    state: latest
  when: ansible_os_family == "RedHat"
