---

- name: ensure dot dir exists
  file:
    path: '~/.aws'
    state: directory
    mode: '0700'

- name: place aws credentials
  template:
    src: aws_credentials.j2
    dest: '~/.aws/credentials'
    mode: '0600'

- name: place aws config
  template:
    src: aws_config.j2
    dest: '~/.aws/config'
    mode: '0600'
