---
# dataverse/tasks/dataverse-install.yml

# version numbers changed on github. only used this because files were missing from install.zip
#- name: clone {{ dataverse.version }} from git. optimally replace install.zip with this.
#  git: repo=git://github.com/IQSS/dataverse.git dest=/tmp/dataverse_{{ dataverse.version }} version={{ dataverse.version }}
#       clone=yes depth=1 accept_hostkey=true

- name: run dataverse installer
  debug:
    msg: '##### DATAVERSE INSTALLER #####'

- include: dataverse-build.yml
  when: dataverse_branch != "release"
  
- name: fix perms on dataverse-war
  file: path=/tmp/dvinstall/dataverse.war mode=0644

- name: grab current copies of installer source
  get_url:
    url: 'https://raw.githubusercontent.com/IQSS/dataverse/develop/scripts/installer/{{ item }}'
    dest: '/tmp/dvinstall/{{ item }}'
    mode: '0755'
  with_items:
    - install.py
    - installConfig.py
    - installAppServer.py
    - installUtils.py
    - as-setup.sh
  when: dataverse.payara.zipurl is not match(".*glassfish-4.1.zip")

- name: grab api setup scripts as well
  get_url:
    url: 'https://raw.githubusercontent.com/IQSS/dataverse/develop/scripts/api/{{ item }}'
    dest: '/tmp/dvinstall/{{ item }}'
    mode: '0755'
  with_items:
    - setup-all.sh
    - setup-datasetfields.sh
    - setup-builtin-roles.sh
    - setup-identity-providers.sh
  when: dataverse.payara.zipurl is not match(".*glassfish-4.1.zip")

- name: set dataverse adminpass in setup-all
  lineinfile:
    path: /tmp/dvinstall/setup-all.sh
    regexp: '^DV_SU_PASSWORD'
    line: 'DV_SU_PASSWORD="{{ dataverse.adminpass }}"'

- name: bash aliases won't expand in non-interactive shells
  lineinfile:
    path: /tmp/dvinstall/as-setup.sh
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: 'rserve_password_alias', line: '  ./asadmin $ASADMIN_OPTS create-jvm-options "\-Ddataverse.rserve.password=${RSERVE_PASS}"' }
    - { regexp: 'doi_password_alias', line: '  ./asadmin $ASADMIN_OPTS create-jvm-options "\-Ddoi.password=${DOI_PASSWORD}"' }
    - { regexp: 'db_password_alias', line: '  ./asadmin $ASADMIN_OPTS set "resources.jdbc-connection-pool.dvnDbPool.property.password=${DB_PASS}"' }
  when: dataverse.payara.zipurl is not match(".*glassfish-4.1.zip")

- name: ensure as-setup.sh is executable
  file:
    path: /tmp/dvinstall/as-setup.sh
    mode: 0755
  when: dataverse.payara.zipurl is not match(".*glassfish-4.1.zip")

- name: register default_config
  set_fact:
    default_config: '{{ dataverse.default.config }}'

- name: place default.config template
  template:
    src: default.config.j2
    dest: /tmp/dvinstall/default.config
    owner: root
    group: root
    mode: 0644
  when: default_config|length == 0

- name: place default.config
  copy:
    src: default.config
    dest: /tmp/dvinstall/default.config
    owner: '{{ dataverse.payara.user }}'
    group: '{{ dataverse.payara.group }}'
    mode: 0600
  when: default_config|length > 0

- include: jacoco-instrument.yml
  when: dataverse.jacoco.enabled == true and
        dataverse_repo != "release"

- name: allow installer write access
  file:
    path: /tmp/dvinstall
    owner: '{{ dataverse.payara.user }}'

- name: patch installAppServer.py so that FILES_DIR points to the correct location
  lineinfile:
    path: /tmp/dvinstall/installAppServer.py
    regexp: "^   os.environ..FILES_DIR.. = "
    line: "   os.environ['FILES_DIR'] = \"{{ dataverse.filesdirs[0].path }}\""
  when: dataverse.filesdirs[0] is defined and
        dataverse.payara.zipurl is not match(".*glassfish-4.1.zip")

- name: patch as-setup.sh so it doesn't hardcode siteUrl
  lineinfile:
    path: /tmp/dvinstall/as-setup.sh
    regexp: '(.*)-Ddataverse.siteUrl(.*)'
    line: '  ./asadmin $ASADMIN_OPTS create-jvm-options "\-Ddataverse.siteUrl={{ siteUrl }}"'
  when: dataverse.payara.zipurl is not match(".*glassfish-4.1.zip")

- name: fire off installer
  shell: '/usr/bin/python /tmp/dvinstall/install.py -f --config_file=default.config --noninteractive > /tmp/dvinstall/install.out 2>&1'
  become: yes
  become_user: '{{ dataverse.payara.user }}'
  args:
    chdir: /tmp/dvinstall

# install.py doesn't currently log this output, nothing sensitive in install.out
#- name: negate need for password aliases
#  file:
#    name: /tmp/as-setup.out
#    mode: 0600
#  ignore_errors: yes

- name: set logging format
  become: yes
  become_user: "{{ dataverse.payara.user }}"
  shell: "{{ payara_dir }}/bin/asadmin set-log-file-format {{ dataverse.payara.logformat }}"

