# datavarse/tasks/dataverse-build.yml

- name: build warfile
  debug:
    msg: '##### BUILD WARFILE #####'

- name: install maven
  yum:
    name: maven
    state: latest

- name: maven rpm requires openjdk-1.8 but maybe we want newer
  alternatives:
    name: '{{ item.name }}'
    link: '{{ item.link }}'
    path: '{{ item.path }}'
  with_items:
    - { name: 'java', link: '/usr/bin/java', path: '/usr/lib/jvm/java-{{ java.version }}-openjdk/bin/java'}
    - { name: 'javac', link: '/usr/bin/javac', path: '/usr/lib/jvm/java-{{ java.version }}-openjdk/bin/javac'}
  when: ansible_os_family == "RedHat" and
        java.version != '1.8.0'

- name: get branch_commit
  shell: 'cd "{{ dataverse.srcdir }}" && git log --oneline | head -1 | awk "{print $1}"'
  register: bcout

- set_fact:
    commit='{{ bcout.stdout.split(" ")[0] }}'

- set_fact:
    jacoco_arg=''

- set_fact:
    jacoco_arg='-Djacoco.skip.instrument=false'
  when: dataverse.jacoco.enabled == true

- name: add branch name, branch_commit to BuildNumber.properties
  lineinfile:
    path: "{{ dataverse.srcdir }}/src/main/java/BuildNumber.properties"
    line: "build.number={{ dataverse_branch }}-{{ commit }}"
    create: yes

- name: build warfile with default tests. tail /tmp/dataverse/mvn.out for gory details.
  shell: "export JAVA_HOME=/usr/lib/jvm/java-{{ java.version}} && mvn -T 2C package -Dmaven.test.skip=true > mvn.out"
  args:
    chdir: "{{ dataverse.srcdir }}"
  when: dataverse.unittests.enabled == false

- name: build warfile with specified tests. tail /tmp/dataverse/mvn.out for gory details.
  shell: "mvn {{ dataverse.unittests.argument }} {{ jacoco_arg }} -T 2C package > mvn.out"
  args:
    chdir: "{{ dataverse.srcdir }}"
  when: dataverse.unittests.enabled == true

- name: copy warfile over release
  copy:
    src: '{{ dataverse.srcdir }}/target/dataverse-{{ dataverse.version }}.war'
    dest: '/tmp/dvinstall/dataverse.war'
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- name: place redeploy script
  template:
    src: redeploy.sh.j2
    dest: '{{ dataverse.srcdir }}/redeploy.sh'
    owner: root
    group: root
    mode: 0755
