---

- name: install docker-ce
  ansible.builtin.dnf:
    name: ['docker-ce','docker-ce-cli','containerd.io','docker-compose','python-docker-py']
    enablerepo: '{{ docker.repo }}'
    state: latest

- name: ensure /etc/docker exists
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755

- name: configure cidr range
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  when: localstack.docker.cidr is undefined

- name: add ansible_user to docker group
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes

- name: reload systemd, enable docker, start
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: started
