---

- name: install docker-ce repo
  ansible.builtin.get_url:
    url: '{{ docker.repo }}'
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'

- name: install docker-ce
  ansible.builtin.dnf:
    name: ['docker-ce', 'docker-compose-plugin']
    state: latest

# this breaks on RHEL9. let's use 'docker compose' instead
#- name: Ansible docker module requires python-docker
#  ansible.builtin.package:
#    name: 'python3-docker'
#    state: latest
#
#- name: pip must update itself
#  ansible.builtin.pip:
#    name: pip
#    executable: pip3
#    state: latest
#
#- name: and docker-compose python package
#  ansible.builtin.pip:
#    name: docker-compose

- name: ensure /etc/docker exists
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755

- name: configure cidr range
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  when: docker.cidr is undefined

- name: reload systemd, enable docker, start
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: started
