---

- name: install docker-ce repo
  ansible.builtin.get_url:
    url: '{{ docker.repo }}'
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'

- name: install docker-ce
  ansible.builtin.dnf:
    name: ['docker-ce']
    state: latest

- name: ensure /etc/docker exists
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755

- name: configure cidr range
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  when: docker.cidr is undefined

- name: add ansible_ssh_user to docker group
  ansible.builtin.user:
    name: '{{ ansible_ssh_user }}'
    groups: docker
    append: yes

- name: reload systemd, enable docker, start
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: started
