---

# for reference
#    vars:
#      label: "{{ item.label }}"
#      custom_endpoint_url: "{{ item.custom_endpoint_url }}"
#      custom_endpoint_region: "{{ item.region }}"
#      bucket_name: "{{ item.bucket_name }}"
#      path_style_access: "{{ item.path_style_access }}"
#      upload_redirect: "{{ item.upload_redirect }}"
#      download_redirect: "{{ item.download_redirect }}"

- name: escape custom endpoint url colons
  ansible.builtin.set_fact: "custom_endpoint_escaped={{ item.custom_endpoint_url | regex_replace (':','\\:') }}"
  when: item.custom_endpoint_url | length > 0

- name: create localstack bucket for testing
  shell: 'aws --endpoint={{ custom_endpoint_escaped }} s3 mb s3://{{ item.bucket_name }}'
  when: item.custom_endpoint_url | length > 0

# todo: do we need this?
#- name: set CORS on bucket when upload_redirect is true

- name: set Payara JVM options  
  become: yes
  become_user: "{{ dataverse.payara.user }}"
  shell: "{{ payara_dir }}/bin/asadmin create-jvm-options -Ddataverse.{{ item.label }}.{{ item.key }}={{ item.value}}"
  with_items:
    - { 'key': 'type' , ' value': 's3' }
    - { 'key': 'label' , 'value': '{{ item.label }}' }
    - { 'key': 'bucket-name' , 'value': '{{ item.bucket_name }}' }
    - { 'key': 'custom-endpoint-url' , 'value': '{{ item.custom_endpoint_url }}' }
    - { 'key': 'custom-endpoint-region' , 'value': '{{ item.custom_endpoint_region }}' }
    - { 'key': 'path-style-access' , 'value': '{{ item.path_style_access }}' }
    - { 'key': 'upload-redirect' , 'value': '{{ item.upload_redirect }}' }
    - { 'key': 'download-redirect' , 'value': '{{ item.download_redirect }}' }
