---

- ansible.builtin.import_tasks: docker.yml

# so we can run localstack task stand-alone
- ansible.builtin.import_tasks: dataverse-fqdn.yml

- name: is hostname_external set
  ansible.builtin.set_fact:
    hostname_external: '{{ public_fqdn }}'
  when: localstack.hostname_external is undefined

- name: place docker-compose.yml template
  ansible.builtin.template:
    src: localstack-compose.yml.j2
    dest: '{{ ansible_env.HOME }}/localstack-compose.yml'

- name: ensure DATA_DIR exists
  ansible.builtin.file:
    path: '{{ localstack.data_dir }}'
    state: directory
    mode: 0777

- name: start s3-test container
  ansible.builtin.shell: 'docker-compose -f localstack-compose.yml up -d'
  args:
    chdir: '{{ ansible_env.HOME }}'
