---

- name: install prometheus
  debug:
    msg: '##### PROMETHEUS #####'
  tags: prometheus

- name: systemd no likey escaped colons
  set_fact:
    siteUrl: "{{ siteUrl | regex_replace('\\\\:', ':') }}"
  tags: prometheus

- debug:
    msg: "siteUrl is {{ siteUrl }}"

- name: Put SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive
  tags: prometheus

- include: collectd.yml
  tags: prometheus

- name: add prometheus service account
  user:
    name: '{{ prometheus.user }}'
  tags: prometheus

# firewalld is outside the role scope
#- name: punch prometheus firewall holes
#  firewalld:
#    port: '{{ item }}'
#    permanent: yes
#    state: enabled
#  with_items:
#  - 9090/tcp
#  - 9100/tcp

- name: unarchive won't create directory
  file:
    path: '{{ prometheus.root }}'
    state: directory
    owner: '{{ prometheus.user }}'
    mode: '0755'
  tags: prometheus

- name: install prometheus
  unarchive:
    src: '{{ prometheus.url }}'
    dest: '{{ prometheus.root }}'
    owner: '{{ prometheus.user }}'
    remote_src: yes
    extra_opts: [--strip-components=1]
  tags: prometheus

- name: copy prometheus config file
  copy:
    src: prometheus.yml
    dest: '{{ prometheus.root }}/prometheus.yml'
    owner: '{{ prometheus.user }}'
    mode: 0644
  tags: prometheus

- name: node_exporter dir must exist
  file:
    path: '{{ prometheus.root }}/node_exporter'
    state: directory
    owner: '{{ prometheus.user }}'
    mode: '0755'
  tags: prometheus

- name: install node_exporter
  unarchive:
    src: '{{ prometheus.node_exporter }}'
    dest: '{{ prometheus.root }}/node_exporter'
    remote_src: yes
    extra_opts: [--strip-components=1]
  tags: prometheus
    
- name: place prometheus systemd template
  template:
    src: prometheus.service.j2
    dest: /usr/lib/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
  tags: prometheus

- name: place node_exporter systemd template
  template:
    src: node_exporter.service.j2
    dest: /usr/lib/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  tags: prometheus

- name: reload systemd
  shell: systemctl daemon-reload
  tags: prometheus

- name: start and enable prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
  tags: prometheus

- name: give prometheus a breather
  pause:
    seconds: 2
  tags: prometheus

- name: start and enable node_exporter
  systemd:
    name: prometheus
    state: started
    enabled: yes
  tags: prometheus

- include: grafana.yml
  tags: grafana
